version: '3.8'

services:
  twilio-webhook:
    build: .
    container_name: twilio-sms-webhook-prod
    ports:
      - "5002:5002"
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    restart: always
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5002/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - twilio-network
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  twilio-network:
    driver: bridge 