version: '3.8'

services:
  twilio-webhook:
    build: .
    container_name: twilio-sms-webhook
    ports:
      - "5002:5002"
    environment:
      - PYTHONUNBUFFERED=1
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
    env_file:
      - .env
    volumes:
      # Mount source code for development (optional - remove for production)
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5002/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - twilio-network

networks:
  twilio-network:
    driver: bridge 